export type FontFamily = "font-raleway" | "font-bungee" | null;
export type FontStyle = "italic" | "not-italic" | null;
export type TextSize = "text-body" | "text-sub" | "text-title" | "text-heading" | "text-display" | null;
export type FontWeight = "font-light" | "font-normal" | "font-medium" | "font-semibold" | "font-bold" | "font-extrabold" | "font-black" | null;
export type Leading = "leading-tight" | "leading-snug" | null;
export type TextAlign = "text-left" | "text-center" | "text-right" | "text-justify" | null;
export type TextColor = "color-blue" | "color-light-blue" | "color-green" | "color-dark-white" | "color-white" | "color-dark" | "color-gold" | null;
export type TextCase = "uppercase" | "lowercase" | null;
export type UlType = "list-disc" | "list-decimal" | "list-none";